services:
  app_aml_mongo:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.aml_mongo
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_AML_MONGO_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $APP_AML_MONGO_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_AML_MONGO_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_AML_MONGO_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5548:8080
